steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/jul365:$COMMIT_SHA",
        "-f",
        "web/Dockerfile",
        "web/",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/jul365:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "set"
      - "image"
      - "deployment/jul365"
      - "jul365-sha256-1=gcr.io/$PROJECT_ID/jul365:$COMMIT_SHA"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=europe-west1-b"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-2"
